package com.scrazy.ey.entity.csdn;

public class CsdnColumnCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csdn_column_category.id
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csdn_column_category.url
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column csdn_column_category.name
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csdn_column_category.id
     *
     * @return the value of csdn_column_category.id
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csdn_column_category.id
     *
     * @param id the value for csdn_column_category.id
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csdn_column_category.url
     *
     * @return the value of csdn_column_category.url
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csdn_column_category.url
     *
     * @param url the value for csdn_column_category.url
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column csdn_column_category.name
     *
     * @return the value of csdn_column_category.name
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column csdn_column_category.name
     *
     * @param name the value for csdn_column_category.name
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

	@Override
	public String toString() {
		return "CsdnColumnCategory [id=" + id + ", url=" + url + ", name=" + name + "]";
	}
}