package com.scrazy.ey.dao.csdn;

import java.util.List;

import com.scrazy.ey.entity.csdn.CsdnColumnCategory;

public interface CsdnColumnCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csdn_column_category
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csdn_column_category
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    int insert(CsdnColumnCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csdn_column_category
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    int insertSelective(CsdnColumnCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csdn_column_category
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    CsdnColumnCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csdn_column_category
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    int updateByPrimaryKeySelective(CsdnColumnCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csdn_column_category
     *
     * @mbggenerated Sat Jul 23 15:20:53 CST 2016
     */
    int updateByPrimaryKey(CsdnColumnCategory record);
    
    List<CsdnColumnCategory>selectAll();
}