package com.scrazy.ey.dao.csdn;

import java.util.List;

import com.scrazy.ey.entity.csdn.CsdnColumnProfile;

public interface CsdnColumnProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csdn_column_profile
     *
     * @mbggenerated Sat Jul 23 18:02:01 CST 2016
     */
    int deleteByPrimaryKey(String columnurl);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csdn_column_profile
     *
     * @mbggenerated Sat Jul 23 18:02:01 CST 2016
     */
    int insert(CsdnColumnProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csdn_column_profile
     *
     * @mbggenerated Sat Jul 23 18:02:01 CST 2016
     */
    int insertSelective(CsdnColumnProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csdn_column_profile
     *
     * @mbggenerated Sat Jul 23 18:02:01 CST 2016
     */
    CsdnColumnProfile selectByPrimaryKey(String columnurl);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csdn_column_profile
     *
     * @mbggenerated Sat Jul 23 18:02:01 CST 2016
     */
    int updateByPrimaryKeySelective(CsdnColumnProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table csdn_column_profile
     *
     * @mbggenerated Sat Jul 23 18:02:01 CST 2016
     */
    int updateByPrimaryKey(CsdnColumnProfile record);
    
    void InsertMoreItem(List<CsdnColumnProfile> list);
}